### PR TITLE
implement codes from Aaron

### PR DESCRIPTION
**Pull request by ysonggit**
Waypoint updater (partial):

> Waypoint Updater Node (Partial): Complete a partial waypoint updater which subscribes to /base_waypoints and /current_pose and publishes to /final_waypoints.

Snapshots:

waypointupdater

### CODE REVIEW

**Comment by ysonggit** [comment]
@emabello42 simply apply Aaron's solution, as a result, the car can publish a topic of `/final_waypoints`, please double check. 

@FRathmann FYI, please checkout this branch to unblock your work, let me know if you can subscribe the `/final_waypoints` topic.

**Review by emabello42 — APPROVED** [review]
Hi Jay,
I tested it and generates the points to follow in front of the car. It should be now integrated and tested with the DBW node.

**Comment by ysonggit** [comment]
thank you @emabello42

**Comment by FRathmann** [comment]
nice work. I'll check out the branch later and test the final_waypoints topic.

**Comment by pperle** [comment]
Maybe switching from `KDTree` to `cKDTree` is a good idea. It will speed up the calculations as it is implemented in Cython.

https://docs.scipy.org/doc/scipy-0.19.1/reference/generated/scipy.spatial.cKDTree.html

**Comment by ysonggit** [comment]
@pperle thank you for your idea, will create another PR to try the cKDTree

**Pull request merged**
