### PR TITLE
FIX: printing detector logs from callback function intervenes the car's PID response

### PR DESCRIPTION
**Pull request by ysonggit**
The latest merge breaks the car's lane following behavior because of the too frequent logging messages in the `image_cb()` function. 

@pperle if you test the current master branch with the autonomous mode, you will see the car cannot follow the lane.

### CODE REVIEW

**Comment by pperle** [comment]
These prints are not important right now so they can be ignored. Maybe we should make a `DEBUG` variable for each node.

**Comment by emabello42** [comment]
Although removing the prints improves the driving, after some time the car deviates from the waypoint path. Someone else is experimenting the same problem? I tested in my VM, and in my PC using docker.

**Comment by ysonggit** [comment]
@emabello42 you are right, the problem I observe is: everytime when I toggle the "camera" option of the simulator, the car can not follow the waypoints, regardless of the prints.

**Comment by ysonggit** [comment]
close this PR for now as it is not the right solution.

**Pull request closed without merging**
